@startuml
hide circle
skinparam classAttributeIconSize 0

Class "{abstract}\nCommand" as Command {
  +execute(Model): CommandResult
}
Class NoteCommand {
  +COMMAND_WORD: String
  +MESSAGE_USAGE: String
  +MESSAGE_ARGUMENTS: String
  +MESSAGE_ADD_NOTE_SUCCESS: String
  +MESSAGE_DELETE_NOTE_SUCCESS: String
  +execute(Model): CommandResult
  -generateSuccessMessage(Person): String
}
Class CommandException

NoteCommand -up-|> Command
Command ..> CommandException: throws >
NoteCommand .right.> CommandException: throws >
@enduml
