@startuml
hide circle
skinparam classAttributeIconSize 0

Class "{abstract}\nCommand" as Command {
  +execute(Model): CommandResult
}
Class NoteCommand {
  <u>+COMMAND_WORD: String
  <u>+MESSAGE_USAGE: String
  <u>+MESSAGE_ARGUMENTS: String
  <u>+MESSAGE_ADD_NOTE_SUCCESS: String
  <u>+MESSAGE_DELETE_NOTE_SUCCESS: String
  -index: Index
  -note: Note
  -isInitiating: boolean
  +execute(Model): CommandResult
  -generateSuccessMessage(Person): String
}
Class CommandException

NoteCommand -up-|> Command
Command ..> CommandException: throws >
NoteCommand .right.> CommandException: throws >
@enduml
