@startuml
!include style.puml
skinparam ArrowFontStyle plain

Actor User as user USER_COLOR
Participant ":UI" as ui UI_COLOR
Participant ":Logic" as logic LOGIC_COLOR
Participant ":Model" as model MODEL_COLOR
Participant ":File" as file STORAGE_COLOR

user -[USER_COLOR]> ui : "export f/data/addressbook.json"
activate ui UI_COLOR

ui -[UI_COLOR]> logic : execute("export f/data/addressbook.json")
activate logic LOGIC_COLOR

create file
logic -[LOGIC_COLOR]> file : new Storage()

logic -[LOGIC_COLOR]> model : getAddressBook()
activate model MODEL_COLOR

model -[MODEL_COLOR]-> logic : addressBook
deactivate model

logic -[LOGIC_COLOR]> file : readAddressBook()
activate file STORAGE_COLOR_T1
file -[STORAGE_COLOR]> file: read file
activate file STORAGE_COLOR_T1
deactivate file
file --[STORAGE_COLOR]> logic : newAddressBook
deactivate file

logic -[LOGIC_COLOR]> model : setAddressBook(newAddressBook)
activate model MODEL_COLOR

model -[MODEL_COLOR]-> logic
deactivate model

logic --[LOGIC_COLOR]> ui
deactivate logic

ui--[UI_COLOR]> user
deactivate ui
@enduml
