@startuml
!include style.puml
skinparam ArrowFontStyle plain

Actor User as user USER_COLOR
Participant ":UI" as ui UI_COLOR
Participant ":Logic" as logic LOGIC_COLOR
Participant ":Model" as model MODEL_COLOR
Participant ":Storage" as storage STORAGE_COLOR

user -[USER_COLOR]> ui : "export f/data/addressbook.csv t/tag1 t/tag2"
activate ui UI_COLOR

ui -[UI_COLOR]> logic : execute("export f/data/addressbook.csv t/tag1 t/tag2")
activate logic LOGIC_COLOR

create storage
logic -[LOGIC_COLOR]> storage : new Storage()

logic -[LOGIC_COLOR]> model : getAddressBook()
activate model MODEL_COLOR

model -[MODEL_COLOR]-> logic : addressBook
deactivate model

logic -[LOGIC_COLOR]> logic : filterAddressBook(tags)
activate logic LOGIC_COLOR_T1
deactivate logic

logic -[LOGIC_COLOR]> storage : saveAddressBook()
activate storage STORAGE_COLOR
storage -[STORAGE_COLOR]> storage: write file
activate storage STORAGE_COLOR_T1
deactivate storage
deactivate storage

logic --[LOGIC_COLOR]> ui
deactivate logic

ui--[UI_COLOR]> user
deactivate ui
@enduml
