@startuml
!include style.puml
skinparam ArrowFontStyle plain

Actor User as user USER_COLOR
Participant ":UI" as ui UI_COLOR
Participant ":Logic" as logic LOGIC_COLOR
Participant ":Model" as model MODEL_COLOR
Participant ":Storage" as storage STORAGE_COLOR

user -[USER_COLOR]> ui : "import f/data/addressbook.json"
activate ui UI_COLOR

ui -[UI_COLOR]> logic : execute("import f/data/addressbook.json")
activate logic LOGIC_COLOR

logic -[LOGIC_COLOR]> model : setAddressBookFilePath(filepath)
activate model MODEL_COLOR

model -[MODEL_COLOR]-> logic
deactivate model

create storage
logic -[LOGIC_COLOR]> storage : new Storage(filepath)

logic -[LOGIC_COLOR]> storage : readAddressBook()
activate storage STORAGE_COLOR_T1
storage -[STORAGE_COLOR]> storage: read file
activate storage STORAGE_COLOR_T1
deactivate storage
storage --[STORAGE_COLOR]> logic : newAddressBook
deactivate storage

logic -[LOGIC_COLOR]> model : setAddressBook(newAddressBook)
activate model MODEL_COLOR

model -[MODEL_COLOR]-> logic
deactivate model

logic --[LOGIC_COLOR]> ui
deactivate logic

ui--[UI_COLOR]> user
deactivate ui
@enduml
