@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":VersionedAddressBook" as VersionedAddressBook MODEL_COLOR
end box

[-> Model : undoAddressBook()
activate Model

Model -> VersionedAddressBook : undo()
activate VersionedAddressBook

VersionedAddressBook -> VersionedAddressBook2 : undo()
activate VersionedAddressBook2

VersionedAddressBook2 -> VersionedAddressBook2 :clear RedoStack(ReadOnlyAddressBook)
VersionedAddressBook2 --> VersionedAddressBook :
deactivate VersionedAddressBook2

VersionedAddressBook -> VersionedAddressBook :clear RedoStack(ReadOnlyAddressBook)
VersionedAddressBook --> Model :
deactivate VersionedAddressBook

[<-- Model
deactivate Model

@enduml
